-- =============================================
-- Sync Metadata Table
-- Tracks last sync timestamp per table for incremental syncing
-- Run this in Supabase SQL Editor
-- =============================================

CREATE TABLE IF NOT EXISTS sync_metadata (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  table_name TEXT UNIQUE NOT NULL,
  last_sync_timestamp TIMESTAMP WITH TIME ZONE,
  last_sync_duration_ms INT,
  last_sync_status TEXT DEFAULT 'pending',
  records_fetched INT DEFAULT 0,
  records_upserted INT DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast lookup by table name
CREATE INDEX IF NOT EXISTS idx_sync_metadata_table_name ON sync_metadata(table_name);

-- Grant access to service role (used by Netlify functions)
GRANT ALL ON sync_metadata TO service_role;
GRANT SELECT ON sync_metadata TO authenticated;
GRANT SELECT ON sync_metadata TO anon;

-- Insert initial rows for all synced tables (first sync will be full)
INSERT INTO sync_metadata (table_name, last_sync_status) VALUES
  ('heartbeats', 'pending'),
  ('stammdaten', 'pending'),
  ('airtable_displays', 'pending'),
  ('tasks', 'pending'),
  ('acquisition', 'pending'),
  ('dayn_screens', 'pending'),
  ('installationen', 'pending'),
  ('hardware_ops', 'pending'),
  ('hardware_sim', 'pending'),
  ('hardware_displays', 'pending'),
  ('chg_approvals', 'pending'),
  ('hardware_swaps', 'pending'),
  ('hardware_deinstalls', 'pending'),
  ('communications', 'pending')
ON CONFLICT (table_name) DO NOTHING;
